name: Compilar Arch-WM APK (Definitivo)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Validar Arquivos na Raiz
        run: |
          echo "Verificando se main.py e buildozer.spec existem:"
          ls -la

      - name: Configurar Java 21 Recente
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true

      - name: Configurar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar Dependências e Buildozer
        run: |
          sudo apt-get update && sudo apt-get install -y \
            git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev libffi-dev libssl-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
          pip install --upgrade pip
          pip install --upgrade buildozer cython

      - name: Executar Compilação do APK
        run: |
          buildozer android release

      - name: Organizar Artefatos Binários
        run: |
          mkdir -p final_apk
          cp bin/*.apk final_apk/

      - name: Salvar APK nos Artefatos do GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ArchWM-Wayland-Final
          path: final_apk/*.apk
          
